// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivwmiwagadrjnvudagio.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2d21pd2FnYWRyam52dWRhZ2lvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzYyNzE0MjksImV4cCI6MjA1MTg0NzQyOX0.HypRNSZnxWpGIy7HSNJ_HUGmlLh2181RnXnAQII0b9s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);